// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymimecsuurziargyhjmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaW1lY3N1dXJ6aWFyZ3loam1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU2MTIsImV4cCI6MjA2MTE4MTYxMn0.DKN4Tz7R0zR0vZWevA4CGk8dujihtr0ccuViWkRDB-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);